#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PrintBot.Droid.Resource", IsApplication=true)]

namespace PrintBot.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLStorage.Resource.String.ApplicationName = global::PrintBot.Droid.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::PrintBot.Droid.Resource.String.Hello;
			global::com.refractored.fab.Resource.Attribute.fab_colorDisabled = global::PrintBot.Droid.Resource.Attribute.fab_colorDisabled;
			global::com.refractored.fab.Resource.Attribute.fab_colorNormal = global::PrintBot.Droid.Resource.Attribute.fab_colorNormal;
			global::com.refractored.fab.Resource.Attribute.fab_colorPressed = global::PrintBot.Droid.Resource.Attribute.fab_colorPressed;
			global::com.refractored.fab.Resource.Attribute.fab_colorRipple = global::PrintBot.Droid.Resource.Attribute.fab_colorRipple;
			global::com.refractored.fab.Resource.Attribute.fab_shadow = global::PrintBot.Droid.Resource.Attribute.fab_shadow;
			global::com.refractored.fab.Resource.Attribute.fab_size = global::PrintBot.Droid.Resource.Attribute.fab_size;
			global::com.refractored.fab.Resource.Attribute.layoutManager = global::PrintBot.Droid.Resource.Attribute.layoutManager;
			global::com.refractored.fab.Resource.Attribute.reverseLayout = global::PrintBot.Droid.Resource.Attribute.reverseLayout;
			global::com.refractored.fab.Resource.Attribute.spanCount = global::PrintBot.Droid.Resource.Attribute.spanCount;
			global::com.refractored.fab.Resource.Attribute.stackFromEnd = global::PrintBot.Droid.Resource.Attribute.stackFromEnd;
			global::com.refractored.fab.Resource.Color.fab_material_blue_500 = global::PrintBot.Droid.Resource.Color.fab_material_blue_500;
			global::com.refractored.fab.Resource.Dimension.fab_elevation_lollipop = global::PrintBot.Droid.Resource.Dimension.fab_elevation_lollipop;
			global::com.refractored.fab.Resource.Dimension.fab_scroll_threshold = global::PrintBot.Droid.Resource.Dimension.fab_scroll_threshold;
			global::com.refractored.fab.Resource.Dimension.fab_shadow_size = global::PrintBot.Droid.Resource.Dimension.fab_shadow_size;
			global::com.refractored.fab.Resource.Dimension.fab_size_mini = global::PrintBot.Droid.Resource.Dimension.fab_size_mini;
			global::com.refractored.fab.Resource.Dimension.fab_size_normal = global::PrintBot.Droid.Resource.Dimension.fab_size_normal;
			global::com.refractored.fab.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame = global::PrintBot.Droid.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame;
			global::com.refractored.fab.Resource.Drawable.fab_shadow = global::PrintBot.Droid.Resource.Drawable.fab_shadow;
			global::com.refractored.fab.Resource.Drawable.fab_shadow_mini = global::PrintBot.Droid.Resource.Drawable.fab_shadow_mini;
			global::com.refractored.fab.Resource.Id.item_touch_helper_previous_elevation = global::PrintBot.Droid.Resource.Id.item_touch_helper_previous_elevation;
			global::com.refractored.fab.Resource.Id.mini = global::PrintBot.Droid.Resource.Id.mini;
			global::com.refractored.fab.Resource.Id.normal = global::PrintBot.Droid.Resource.Id.normal;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton = global::PrintBot.Droid.Resource.Styleable.FloatingActionButton;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorDisabled = global::PrintBot.Droid.Resource.Styleable.FloatingActionButton_fab_colorDisabled;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorNormal = global::PrintBot.Droid.Resource.Styleable.FloatingActionButton_fab_colorNormal;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorPressed = global::PrintBot.Droid.Resource.Styleable.FloatingActionButton_fab_colorPressed;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorRipple = global::PrintBot.Droid.Resource.Styleable.FloatingActionButton_fab_colorRipple;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_shadow = global::PrintBot.Droid.Resource.Styleable.FloatingActionButton_fab_shadow;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_size = global::PrintBot.Droid.Resource.Styleable.FloatingActionButton_fab_size;
			global::com.refractored.fab.Resource.Styleable.RecyclerView = global::PrintBot.Droid.Resource.Styleable.RecyclerView;
			global::com.refractored.fab.Resource.Styleable.RecyclerView_android_orientation = global::PrintBot.Droid.Resource.Styleable.RecyclerView_android_orientation;
			global::com.refractored.fab.Resource.Styleable.RecyclerView_layoutManager = global::PrintBot.Droid.Resource.Styleable.RecyclerView_layoutManager;
			global::com.refractored.fab.Resource.Styleable.RecyclerView_reverseLayout = global::PrintBot.Droid.Resource.Styleable.RecyclerView_reverseLayout;
			global::com.refractored.fab.Resource.Styleable.RecyclerView_spanCount = global::PrintBot.Droid.Resource.Styleable.RecyclerView_spanCount;
			global::com.refractored.fab.Resource.Styleable.RecyclerView_stackFromEnd = global::PrintBot.Droid.Resource.Styleable.RecyclerView_stackFromEnd;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080001
			public const int comparators = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int variable_datatypes = 2131230720;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public const int fab_colorDisabled = 2130771974;
			
			// aapt resource value: 0x7f010005
			public const int fab_colorNormal = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int fab_colorPressed = 2130771972;
			
			// aapt resource value: 0x7f010007
			public const int fab_colorRipple = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int fab_shadow = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int fab_size = 2130771977;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int fab_material_blue_500 = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int printbot_green = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int printbot_orange = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int printbot_purple = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int printbot_red = 2131165188;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040005
			public const int fab_elevation_lollipop = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int fab_scroll_threshold = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int fab_shadow_size = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int fab_size_mini = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int fab_size_normal = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int add_white = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int block_green_bg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int block_orange_bg = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int block_purple_bg = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int block_red_bg = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int blockCorners = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bluetooth_scan = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int bluetooth_scan_small = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int BluetoothIcon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int buttoncolour = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int CodeIcon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int CountingLoopicon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int delayicon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int dustbin = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int dustbin_red = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int EndlessLoopicon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int fab_shadow = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int fab_shadow_mini = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int FileListItemPressed = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int FileListSelector = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Icon = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int iconcountingloop = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int iconendlessloop = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ifthenelseblockicon = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int IfThenElseIcon = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int LEDIcon = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int LEDIcon_alt = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ListIcon = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ModuleIcon = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int MoveIcon = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int MoveIcon_alt = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int OtherIcon = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int play = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int RotateIcon = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int SaveIcon = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int SettingsIcon = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int VariableIcon = 2130837541;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000e
			public const int BlockListItem_Delay_DelayTime = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int BlockListItem_EndBlock_Text = 2131034129;
			
			// aapt resource value: 0x7f050015
			public const int BlockListItem_If_Spinner = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int BlockListItem_If_Value = 2131034134;
			
			// aapt resource value: 0x7f050014
			public const int BlockListItem_If_Variable = 2131034132;
			
			// aapt resource value: 0x7f050018
			public const int BlockListItem_LED_toggleIsOn = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int BlockListItem_Move_Acceleration = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int BlockListItem_Rotate_Degrees = 2131034138;
			
			// aapt resource value: 0x7f05001c
			public const int BlockListItem_Variable_Spinner = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int BlockListItem_Variable_Value = 2131034141;
			
			// aapt resource value: 0x7f050023
			public const int Bluetooth_FoundDevicesTextView = 2131034147;
			
			// aapt resource value: 0x7f050021
			public const int Bluetooth_KnownDevicesTextView = 2131034145;
			
			// aapt resource value: 0x7f050027
			public const int BordEditor_ListView_Row_filename = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int BordEditor_MainLayout = 2131034152;
			
			// aapt resource value: 0x7f05002a
			public const int CodeEditor_FragmentContainer = 2131034154;
			
			// aapt resource value: 0x7f05002c
			public const int CodeEditor_FragmentContainerTools = 2131034156;
			
			// aapt resource value: 0x7f050004
			public const int CodeEditor_SaveButton = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int CodeEditor_SettingsButton = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int CodeEditor_SwitchButton = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int CodeEditor_deleteButton = 2131034115;
			
			// aapt resource value: 0x7f05002d
			public const int CodeView_webView = 2131034157;
			
			// aapt resource value: 0x7f05000a
			public const int CountingLoop_AmountOfLoops = 2131034122;
			
			// aapt resource value: 0x7f050040
			public const int Description = 2131034176;
			
			// aapt resource value: 0x7f05003d
			public const int FileList = 2131034173;
			
			// aapt resource value: 0x7f050008
			public const int Main_addButton = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int Main_deleteButton = 2131034119;
			
			// aapt resource value: 0x7f050044
			public const int Settings_Bluetooth = 2131034180;
			
			// aapt resource value: 0x7f050043
			public const int Settings_ModuleSetup = 2131034179;
			
			// aapt resource value: 0x7f050045
			public const int Settings_Other = 2131034181;
			
			// aapt resource value: 0x7f05003f
			public const int Title = 2131034175;
			
			// aapt resource value: 0x7f050010
			public const int block_endblock_layout = 2131034128;
			
			// aapt resource value: 0x7f050024
			public const int bluetooth_ListViewFoundDevices = 2131034148;
			
			// aapt resource value: 0x7f050022
			public const int bluetooth_ListViewKnownDevices = 2131034146;
			
			// aapt resource value: 0x7f050025
			public const int bluetooth_ProgressBar = 2131034149;
			
			// aapt resource value: 0x7f050020
			public const int bluetooth_ScanButton = 2131034144;
			
			// aapt resource value: 0x7f05001e
			public const int bluetooth_fragment_container = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int bluetooth_listview_name = 2131034143;
			
			// aapt resource value: 0x7f050026
			public const int bluetooth_send_SendButton = 2131034150;
			
			// aapt resource value: 0x7f05003c
			public const int button1 = 2131034172;
			
			// aapt resource value: 0x7f050009
			public const int counting_loop_parent = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int delete_button = 2131034123;
			
			// aapt resource value: 0x7f05003b
			public const int editText1 = 2131034171;
			
			// aapt resource value: 0x7f050012
			public const int endless_loop_parent = 2131034130;
			
			// aapt resource value: 0x7f05002b
			public const int fab = 2131034155;
			
			// aapt resource value: 0x7f05002f
			public const int fileOpenedTextView = 2131034159;
			
			// aapt resource value: 0x7f050013
			public const int if_block_parent = 2131034131;
			
			// aapt resource value: 0x7f05002e
			public const int imageView1 = 2131034158;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f050017
			public const int led_block_parent = 2131034135;
			
			// aapt resource value: 0x7f05003e
			public const int listView_button = 2131034174;
			
			// aapt resource value: 0x7f050041
			public const int main_LastFileList = 2131034177;
			
			// aapt resource value: 0x7f050029
			public const int main_ProgramName = 2131034153;
			
			// aapt resource value: 0x7f050042
			public const int main_TutorialButton = 2131034178;
			
			// aapt resource value: 0x7f050001
			public const int mini = 2131034113;
			
			// aapt resource value: 0x7f05000c
			public const int move_block_parent = 2131034124;
			
			// aapt resource value: 0x7f050002
			public const int normal = 2131034114;
			
			// aapt resource value: 0x7f05000d
			public const int textView1 = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int textView2 = 2131034127;
			
			// aapt resource value: 0x7f050031
			public const int tools_CountingLoop = 2131034161;
			
			// aapt resource value: 0x7f050036
			public const int tools_Delay = 2131034166;
			
			// aapt resource value: 0x7f050032
			public const int tools_EndlessLoop = 2131034162;
			
			// aapt resource value: 0x7f050033
			public const int tools_If = 2131034163;
			
			// aapt resource value: 0x7f050034
			public const int tools_LED = 2131034164;
			
			// aapt resource value: 0x7f050035
			public const int tools_Move = 2131034165;
			
			// aapt resource value: 0x7f050037
			public const int tools_Rotate = 2131034167;
			
			// aapt resource value: 0x7f050038
			public const int tools_Variable = 2131034168;
			
			// aapt resource value: 0x7f050030
			public const int tools_scrollview = 2131034160;
			
			// aapt resource value: 0x7f05001b
			public const int var_block_parent = 2131034139;
			
			// aapt resource value: 0x7f050039
			public const int workspace_delete_button = 2131034169;
			
			// aapt resource value: 0x7f05003a
			public const int workspace_listView = 2131034170;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int actionbar_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int actionbar_main_layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BlockListItem_CountingLoop = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int BlockListItem_Delay = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int BlockListItem_Else = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int BlockListItem_EndBlock = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int BlockListItem_EndlessLoop = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int BlockListItem_If = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int BlockListItem_LED = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int BlockListItem_Move = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int BlockListItem_Rotate = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int BlockListItem_Variable = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int bluetooth_layout = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int bluetooth_listview_item = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int bluetooth_scan_layout = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int bluetooth_send_layout = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int BordEditor_ListView_Row = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int BordEditor_MainLayout = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int CodeEditor_Layout = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int CodeViewFragment = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int delete_block = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int FileOpened = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int fragment_tools = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int fragment_workspace = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int LastUsedFileLayout = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int list_view_item = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int ListRowItem = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int Main = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int Settings_Layout = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int TestActivityLayout = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int Toolbar_CountingLoop = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int Toolbar_Delay = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int Toolbar_EndlessLoop = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int Toolbar_If = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int Toolbar_LED = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int Toolbar_Move = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int Toolbar_Rotate = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int Toolbar_Variable = 2130903077;
			
			// aapt resource value: 0x7f030026
			public const int Variable_Datatype_SpinnerItem = 2130903078;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090002
			public const int BlockLayout = 2131296258;
			
			// aapt resource value: 0x7f090007
			public const int Button = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int Button_basic = 2131296264;
			
			// aapt resource value: 0x7f090001
			public const int CodeText = 2131296257;
			
			// aapt resource value: 0x7f090005
			public const int CommandBlockLayout = 2131296261;
			
			// aapt resource value: 0x7f090004
			public const int IfBlockLayout = 2131296260;
			
			// aapt resource value: 0x7f090003
			public const int LoopBlockLayout = 2131296259;
			
			// aapt resource value: 0x7f090000
			public const int NormalText = 2131296256;
			
			// aapt resource value: 0x7f090006
			public const int VarBlockLayout = 2131296262;
			
			// aapt resource value: 0x7f090009
			public const int delete_block_button = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int delete_block_button_red = 2131296266;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FloatingActionButton = new int[] {
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 2
			public const int FloatingActionButton_fab_colorDisabled = 2;
			
			// aapt resource value: 1
			public const int FloatingActionButton_fab_colorNormal = 1;
			
			// aapt resource value: 0
			public const int FloatingActionButton_fab_colorPressed = 0;
			
			// aapt resource value: 3
			public const int FloatingActionButton_fab_colorRipple = 3;
			
			// aapt resource value: 4
			public const int FloatingActionButton_fab_shadow = 4;
			
			// aapt resource value: 5
			public const int FloatingActionButton_fab_size = 5;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
