#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PrintBot.Droid.Resource", IsApplication=true)]

namespace PrintBot.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLStorage.Resource.String.ApplicationName = global::PrintBot.Droid.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::PrintBot.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05001f
			public const int BordEditor_Bord = 2131034143;
			
			// aapt resource value: 0x7f05001d
			public const int BordEditor_ListView_Row_filename = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int BordEditor_MainLayout = 2131034142;
			
			// aapt resource value: 0x7f050021
			public const int CodeEditor_FragmentContainer = 2131034145;
			
			// aapt resource value: 0x7f050023
			public const int CodeEditor_SettingsButton = 2131034147;
			
			// aapt resource value: 0x7f050022
			public const int CodeEditor_SwitchButton = 2131034146;
			
			// aapt resource value: 0x7f050031
			public const int Description = 2131034161;
			
			// aapt resource value: 0x7f05002e
			public const int FileList = 2131034158;
			
			// aapt resource value: 0x7f050036
			public const int Settings_Bluetooth = 2131034166;
			
			// aapt resource value: 0x7f050035
			public const int Settings_ModuleSetup = 2131034165;
			
			// aapt resource value: 0x7f050037
			public const int Settings_Other = 2131034167;
			
			// aapt resource value: 0x7f050030
			public const int Title = 2131034160;
			
			// aapt resource value: 0x7f05001a
			public const int bluetooth_ListViewFoundDevices = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int bluetooth_ListViewKnownDevices = 2131034137;
			
			// aapt resource value: 0x7f05001b
			public const int bluetooth_ProgressBar = 2131034139;
			
			// aapt resource value: 0x7f050017
			public const int bluetooth_ScanButton = 2131034135;
			
			// aapt resource value: 0x7f050015
			public const int bluetooth_fragment_container = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int bluetooth_listview_name = 2131034134;
			
			// aapt resource value: 0x7f05001c
			public const int bluetooth_send_SendButton = 2131034140;
			
			// aapt resource value: 0x7f050005
			public const int button1 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int button2 = 2131034118;
			
			// aapt resource value: 0x7f05000d
			public const int button3 = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int button4 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int button5 = 2131034128;
			
			// aapt resource value: 0x7f050009
			public const int button7 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int button8 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int button9 = 2131034123;
			
			// aapt resource value: 0x7f05002d
			public const int editText1 = 2131034157;
			
			// aapt resource value: 0x7f050024
			public const int fileOpenedTextView = 2131034148;
			
			// aapt resource value: 0x7f05002f
			public const int listView_button = 2131034159;
			
			// aapt resource value: 0x7f050033
			public const int main_CreateButton = 2131034163;
			
			// aapt resource value: 0x7f050034
			public const int main_LastFileList = 2131034164;
			
			// aapt resource value: 0x7f050032
			public const int main_NewProjectName = 2131034162;
			
			// aapt resource value: 0x7f050020
			public const int main_Sampel = 2131034144;
			
			// aapt resource value: 0x7f050000
			public const int relativeLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int tableLayout1 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int tableRow1 = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int tableRow2 = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int tableRow3 = 2131034119;
			
			// aapt resource value: 0x7f050018
			public const int textView1 = 2131034136;
			
			// aapt resource value: 0x7f050011
			public const int textView10 = 2131034129;
			
			// aapt resource value: 0x7f050003
			public const int textView11 = 2131034115;
			
			// aapt resource value: 0x7f050012
			public const int textView12 = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int textView13 = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int textView14 = 2131034131;
			
			// aapt resource value: 0x7f050008
			public const int textView7 = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int textView8 = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int textView9 = 2131034126;
			
			// aapt resource value: 0x7f050026
			public const int tools_button1 = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int tools_button2 = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int tools_button3 = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int tools_button4 = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int tools_button5 = 2131034154;
			
			// aapt resource value: 0x7f05002b
			public const int tools_button6 = 2131034155;
			
			// aapt resource value: 0x7f050025
			public const int tools_scrollview = 2131034149;
			
			// aapt resource value: 0x7f05002c
			public const int workspace_listView = 2131034156;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BlockDoWhile = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BlockForLoop = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BlockLED = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int BlockMoveMotor = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int BlockVariable = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int BlockWhileLoop = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int bluetooth_layout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int bluetooth_listview_item = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int bluetooth_scan_layout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int bluetooth_send_layout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int BordEditor_ListView_Row = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int BordEditor_MainLayout = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int CodeEditor_Layout = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int FileOpened = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int fragment_tools = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int fragment_workspace = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int LastUsedFileLayout = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int list_view_item = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int ListRowItem = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int Main = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int Settings_Layout = 2130903060;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
