#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PrintBot.Droid.Resource", IsApplication=true)]

namespace PrintBot.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLStorage.Resource.String.ApplicationName = global::PrintBot.Droid.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::PrintBot.Droid.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060001
			public const int comparators = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int variable_datatypes = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int printbot_green = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int printbot_orange = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int printbot_purple = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int printbot_red = 2131034115;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int add_white = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int block_green_bg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int block_orange_bg = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int block_purple_bg = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int block_red_bg = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int blockCorners = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bluetooth_scan = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int bluetooth_scan_small = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int BluetoothIcon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int buttoncolour = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int CodeIcon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int CountingLoopicon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int delayicon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int dustbin = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int dustbin_red = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int EndlessLoopicon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int FileListItemPressed = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int FileListSelector = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Icon = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int IfThenElseIcon = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int LEDIcon = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int LEDIcon_alt = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ListIcon = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ModuleIcon = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int MoveIcon = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int MoveIcon_alt = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int OtherIcon = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int RotateIcon = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int SaveIcon = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int SettingsIcon = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int VariableIcon = 2130837535;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000b
			public const int BlockListItem_Delay_DelayTime = 2131230731;
			
			// aapt resource value: 0x7f08000e
			public const int BlockListItem_EndBlock_Text = 2131230734;
			
			// aapt resource value: 0x7f080012
			public const int BlockListItem_If_Spinner = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int BlockListItem_If_Value = 2131230739;
			
			// aapt resource value: 0x7f080011
			public const int BlockListItem_If_Variable = 2131230737;
			
			// aapt resource value: 0x7f080015
			public const int BlockListItem_LED_toggleIsOn = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int BlockListItem_Move_Acceleration = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int BlockListItem_Rotate_Degrees = 2131230743;
			
			// aapt resource value: 0x7f080019
			public const int BlockListItem_Variable_Spinner = 2131230745;
			
			// aapt resource value: 0x7f08001a
			public const int BlockListItem_Variable_Value = 2131230746;
			
			// aapt resource value: 0x7f080020
			public const int Bluetooth_FoundDevicesTextView = 2131230752;
			
			// aapt resource value: 0x7f08001e
			public const int Bluetooth_KnownDevicesTextView = 2131230750;
			
			// aapt resource value: 0x7f080024
			public const int BordEditor_ListView_Row_filename = 2131230756;
			
			// aapt resource value: 0x7f080025
			public const int BordEditor_MainLayout = 2131230757;
			
			// aapt resource value: 0x7f080027
			public const int CodeEditor_FragmentContainer = 2131230759;
			
			// aapt resource value: 0x7f080028
			public const int CodeEditor_FragmentContainerTools = 2131230760;
			
			// aapt resource value: 0x7f080001
			public const int CodeEditor_SaveButton = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int CodeEditor_SettingsButton = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int CodeEditor_SwitchButton = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int CodeEditor_deleteButton = 2131230720;
			
			// aapt resource value: 0x7f080029
			public const int CodeView_content = 2131230761;
			
			// aapt resource value: 0x7f080007
			public const int CountingLoop_AmountOfLoops = 2131230727;
			
			// aapt resource value: 0x7f08003c
			public const int Description = 2131230780;
			
			// aapt resource value: 0x7f080039
			public const int FileList = 2131230777;
			
			// aapt resource value: 0x7f080005
			public const int Main_addButton = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int Main_deleteButton = 2131230724;
			
			// aapt resource value: 0x7f080040
			public const int Settings_Bluetooth = 2131230784;
			
			// aapt resource value: 0x7f08003f
			public const int Settings_ModuleSetup = 2131230783;
			
			// aapt resource value: 0x7f080041
			public const int Settings_Other = 2131230785;
			
			// aapt resource value: 0x7f08003b
			public const int Title = 2131230779;
			
			// aapt resource value: 0x7f08000d
			public const int block_endblock_layout = 2131230733;
			
			// aapt resource value: 0x7f080021
			public const int bluetooth_ListViewFoundDevices = 2131230753;
			
			// aapt resource value: 0x7f08001f
			public const int bluetooth_ListViewKnownDevices = 2131230751;
			
			// aapt resource value: 0x7f080022
			public const int bluetooth_ProgressBar = 2131230754;
			
			// aapt resource value: 0x7f08001d
			public const int bluetooth_ScanButton = 2131230749;
			
			// aapt resource value: 0x7f08001b
			public const int bluetooth_fragment_container = 2131230747;
			
			// aapt resource value: 0x7f08001c
			public const int bluetooth_listview_name = 2131230748;
			
			// aapt resource value: 0x7f080023
			public const int bluetooth_send_SendButton = 2131230755;
			
			// aapt resource value: 0x7f080038
			public const int button1 = 2131230776;
			
			// aapt resource value: 0x7f080006
			public const int counting_loop_parent = 2131230726;
			
			// aapt resource value: 0x7f080008
			public const int delete_button = 2131230728;
			
			// aapt resource value: 0x7f080037
			public const int editText1 = 2131230775;
			
			// aapt resource value: 0x7f08000f
			public const int endless_loop_parent = 2131230735;
			
			// aapt resource value: 0x7f08002b
			public const int fileOpenedTextView = 2131230763;
			
			// aapt resource value: 0x7f080010
			public const int if_block_parent = 2131230736;
			
			// aapt resource value: 0x7f08002a
			public const int imageView1 = 2131230762;
			
			// aapt resource value: 0x7f080014
			public const int led_block_parent = 2131230740;
			
			// aapt resource value: 0x7f08003a
			public const int listView_button = 2131230778;
			
			// aapt resource value: 0x7f08003d
			public const int main_LastFileList = 2131230781;
			
			// aapt resource value: 0x7f080026
			public const int main_ProgramName = 2131230758;
			
			// aapt resource value: 0x7f08003e
			public const int main_TutorialButton = 2131230782;
			
			// aapt resource value: 0x7f080009
			public const int move_block_parent = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int textView1 = 2131230730;
			
			// aapt resource value: 0x7f08000c
			public const int textView2 = 2131230732;
			
			// aapt resource value: 0x7f08002d
			public const int tools_CountingLoop = 2131230765;
			
			// aapt resource value: 0x7f080032
			public const int tools_Delay = 2131230770;
			
			// aapt resource value: 0x7f08002e
			public const int tools_EndlessLoop = 2131230766;
			
			// aapt resource value: 0x7f08002f
			public const int tools_If = 2131230767;
			
			// aapt resource value: 0x7f080030
			public const int tools_LED = 2131230768;
			
			// aapt resource value: 0x7f080031
			public const int tools_Move = 2131230769;
			
			// aapt resource value: 0x7f080033
			public const int tools_Rotate = 2131230771;
			
			// aapt resource value: 0x7f080034
			public const int tools_Variable = 2131230772;
			
			// aapt resource value: 0x7f08002c
			public const int tools_scrollview = 2131230764;
			
			// aapt resource value: 0x7f080018
			public const int var_block_parent = 2131230744;
			
			// aapt resource value: 0x7f080035
			public const int workspace_delete_button = 2131230773;
			
			// aapt resource value: 0x7f080036
			public const int workspace_listView = 2131230774;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int actionbar_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int actionbar_main_layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BlockListItem_CountingLoop = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int BlockListItem_Delay = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int BlockListItem_Else = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int BlockListItem_EndBlock = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int BlockListItem_EndlessLoop = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int BlockListItem_If = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int BlockListItem_LED = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int BlockListItem_Move = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int BlockListItem_Rotate = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int BlockListItem_Variable = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int bluetooth_layout = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int bluetooth_listview_item = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int bluetooth_scan_layout = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int bluetooth_send_layout = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int BordEditor_ListView_Row = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int BordEditor_MainLayout = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int CodeEditor_Layout = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int CodeViewFragment = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int delete_block = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int FileOpened = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int fragment_tools = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int fragment_workspace = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int LastUsedFileLayout = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int list_view_item = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int ListRowItem = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int Main = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int Settings_Layout = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int Toolbar_CountingLoop = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int Toolbar_Delay = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int Toolbar_EndlessLoop = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int Toolbar_If = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int Toolbar_LED = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int Toolbar_Move = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int Toolbar_Rotate = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int Toolbar_Variable = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int Variable_Datatype_SpinnerItem = 2130903077;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070002
			public const int BlockLayout = 2131165186;
			
			// aapt resource value: 0x7f070007
			public const int Button = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int Button_basic = 2131165192;
			
			// aapt resource value: 0x7f070001
			public const int CodeText = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int CommandBlockLayout = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int IfBlockLayout = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int LoopBlockLayout = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int NormalText = 2131165184;
			
			// aapt resource value: 0x7f070006
			public const int VarBlockLayout = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int delete_block_button = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int delete_block_button_red = 2131165194;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
